# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    target-branch: 'main'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      dev:
        dependency-type: 'development'
      prod:
        dependency-type: 'production'

  - package-ecosystem: 'npm'
    target-branch: 'v1'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      dev:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
      prod:
        dependency-type: 'production'
        update-types:
          - minor
          - patch

  - package-ecosystem: 'npm'
    target-branch: 'v2'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      dev:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
      prod:
        dependency-type: 'production'
        update-types:
          - minor
          - patch

  - package-ecosystem: 'npm'
    target-branch: 'v3'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      dev:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
      prod:
        dependency-type: 'production'
        update-types:
          - minor
          - patch

  - package-ecosystem: 'npm'
    target-branch: 'v4'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      dev:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
      prod:
        dependency-type: 'production'
        update-types:
          - minor
          - patch

  - package-ecosystem: 'npm'
    target-branch: 'v5'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      dev:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
      prod:
        dependency-type: 'production'
        update-types:
          - minor
          - patch

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
