version: 2
updates:
  - package-ecosystem: 'npm'
    target-branch: 'main'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      dev:
        dependency-type: 'development'
      prod:
        dependency-type: 'production'

  # v1..v4 are no longer supported

  - package-ecosystem: 'npm'
    target-branch: 'v5'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    groups:
      dev:
        dependency-type: 'development'
      prod:
        dependency-type: 'production'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
