version: 2
updates:
  - package-ecosystem: 'npm'
    target-branch: 'main'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      npm:
        patterns:
          - '*'

  # v1..v5 are no longer supported

  - package-ecosystem: 'npm'
    target-branch: 'v6'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    groups:
      npm:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'
