name: Publish to npm - beta

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '22'

jobs:
  publish-beta:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Bump to beta version
        run: |
          SHORT_SHA=$(git rev-parse --short=8 HEAD)
          BUILD_DATE=$(date +%Y%m%d)
          BETA_VERSION="0.0.0-beta-$SHORT_SHA-$BUILD_DATE"
          echo "Setting version to $BETA_VERSION"
          npm version "$BETA_VERSION" --no-git-tag-version

      - name: Publish to npm
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
