name: Release

on:
  push:
    branches: [main]

env:
  # npm 11.5.1+ required for trusted publishing
  NODE_VERSION: '24.5.0'

permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm run build

      - name: Create Release Pull Request or Publish to npm (beta)
        if: ${{ github.ref_name == 'main' }}
        id: changesets-beta
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          publish: pnpm run publish:beta
          title: '[beta] Version Packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to npm (stable)
        if: ${{ github.ref_name != 'main' }}
        id: changesets-stable
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          publish: pnpm run publish:stable
          title: ${{ format('[{0}] Version Packages', github.ref_name) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
