name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write # for creating release PR
      pull-requests: write # for creating release PR
      id-token: write # for publishing to npm registry
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          cache: true
          install: true

      - name: Build Package
        run: pnpm run build

      - name: Create Release Pull Request or Publish to npm (beta)
        if: ${{ github.ref_name == 'main' }}
        id: changesets-beta
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          publish: pnpm run publish:beta
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to npm (stable)
        if: ${{ github.ref_name != 'main' }}
        id: changesets-stable
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          publish: pnpm run publish:stable
          title: "chore: version packages ${{ format('({0})', github.ref_name) }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
