name: Release

on:
  push:
    branches: [v6]

env:
  # npm 11.5.1+ required for trusted publishing
  NODE_VERSION: '24.5.0'

permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
            cache: true
            install: true

      - name: Build Package
        run: pnpm run build

      - name: Create Release Pull Request or Publish to npm (beta)
        if: ${{ github.ref_name == 'main' }}
        id: changesets-beta
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          publish: pnpm run publish:beta
          title: '[beta] Version Packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to npm (stable)
        if: ${{ github.ref_name != 'main' }}
        id: changesets-stable
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          publish: pnpm run publish:stable
          title: ${{ format('[{0}] Version Packages', github.ref_name) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
