name: Release

on:
  push:
    branches: [v5]

env:
  NODE_VERSION: '22'

permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm run build

      - name: Create Release Pull Request or Publish to npm (beta)
        if: ${{ github.ref_name == 'main' }}
        id: changesets-beta
        uses: changesets/action@v1
        with:
          publish: pnpm run publish:beta
          title: '[beta] Version Packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish to npm (stable)
        if: ${{ github.ref_name != 'main' }}
        id: changesets-stable
        uses: changesets/action@v1
        with:
          publish: pnpm run publish:stable
          title: ${{ format('[{0}] Version Packages', github.ref_name) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
